name: 'Platform.sh - Successful deploy test'

on:
  workflow_call:
    inputs:
      PLATFORMSH_ID:
        required: true
        type: string
      DEPLOY_STATUS_URL_FILE:
        required: true
        type: string
    secrets:
      PLATFORMSH_KEY:
        required: true

jobs:
  platformsh-deploy-test:
    runs-on: ubuntu-latest
    steps:
      - uses: juliangruber/sleep-action@v1
        with:
          time: 3m
      - uses: actions/checkout@v1
      - uses: xendk/dais@main
        with:
          platform_id: ${{ inputs.PLATFORMSH_ID }}
          platform_key: ${{ secrets.PLATFORMSH_KEY }}
          files: ${{ inputs.DEPLOY_STATUS_URL_FILE }}
      - name: Check latest deploy status
        run: |
          STATUS_URL=$(cat ${{ inputs.DEPLOY_STATUS_URL_FILE }})
          curl "$STATUS_URL" | grep '0'  > /dev/null && echo "PlatformSH silently failed to deploy your PR. Use 'platform log deploy' to find out what went wrong." && exit 2
          echo "PlatformSH successfully deployed your PR."
