name: "Testing action-platformsh-url"

on: pull_request
permissions: write-all

jobs:
  ok-test:
    name: "Testing on a branch that has an active, deployed environment"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./
        with:
          PLATFORMSH_ID: ${{ secrets.TEST_PLATFORMSH_ID }}
          PLATFORMSH_KEY: ${{ secrets.TEST_PLATFORMSH_KEY }}
          ENVIRONMENT_NAME: main

  fail-deploy-test:
    name: "Testing on a environment that has a failed deployment"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./
        id: inactive_url
        continue-on-error: true
        with:
          PLATFORMSH_ID: ${{ secrets.TEST_PLATFORMSH_ID }}
          PLATFORMSH_KEY: ${{ secrets.TEST_PLATFORMSH_KEY }}
          ENVIRONMENT_NAME: main
          DEPLOY_STATUS_PATH: '/sites/default/files/mock-deploy-status'

      - name: Check for failure
        if: ${{ steps.inactive_url.outputs.url }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('The test did not fail as expected.')


  missing-url-test:
    name: "Testing on a environment that that has no URL"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./
        id: missing_url
        continue-on-error: true
        with:
          PLATFORMSH_ID: ${{ secrets.TEST_PLATFORMSH_ID }}
          PLATFORMSH_KEY: ${{ secrets.TEST_PLATFORMSH_KEY }}
          ENVIRONMENT_NAME: main
          DEPLOY_STATUS_PATH: '/sites/default/files/xxx-deploy-status'

      - name: Check for failure
        if: ${{ steps.missing_url.outputs.url }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('The test did not fail as expected.')
